"""
Generate the GitHub Pages index.html for the DevOps study-guide site.
Called by .github/workflows/pages.yml during the site build step.

Usage:
    python study-guide/build_index.py _site/
"""

from __future__ import annotations

from pathlib import Path
import sys

BOOKS = [
    (
        "book-1-git-github-actions.html",
        "Book I",
        "Git & GitHub Actions",
        "Git internals, OIDC pipelines, CI/CD gate design, supply-chain security",
    ),
    (
        "book-2-jenkins.html",
        "Book II",
        "Jenkins",
        "Controller-Agent model, Shared Libraries, pipeline-in-a-function pattern",
    ),
    (
        "book-3-docker.html",
        "Book III",
        "Docker",
        "Union filesystem, multi-stage builds, security hardening, Compose architecture",
    ),
    (
        "book-4-kubernetes.html",
        "Book IV",
        "Kubernetes",
        "Desired-state engine, health probes, HPA, RBAC, canary deployments",
    ),
    (
        "book-5-ansible.html",
        "Book V",
        "Ansible",
        "Idempotent playbooks, roles, Vault, agentless SSH automation",
    ),
    (
        "book-6-terraform.html",
        "Book VI",
        "Terraform",
        "HCL deep dive, state management, Atlantis GitOps, provider pinning",
    ),
    (
        "book-7-monitoring-observability.html",
        "Book VII",
        "Monitoring & Observability",
        "SLO/SLI/SLA, Prometheus, ELK, distributed tracing, on-call framework",
    ),
    (
        "book-8-branch-protection-ci-checks.html",
        "Book VIII",
        "Branch Protection & CI Checks",
        "Required checks, CODEOWNERS, ruff, isort, protection tests, GitHub Pages",
    ),
]

CSS = """
:root {
  --navy:#0c2340; --teal:#0ea5a4; --ink:#1a2733; --muted:#556070;
}
* { box-sizing:border-box; margin:0; padding:0; }
body {
  font-family:"Segoe UI Variable Display","Segoe UI",system-ui,sans-serif;
  background: linear-gradient(150deg,#071524 0%,#0c2340 50%,#112f5a 100%);
  min-height:100vh; color:#e8f0fb; padding:40px 20px;
}
.hero { text-align:center; margin-bottom:48px; }
.hero .kicker {
  letter-spacing:.25em; text-transform:uppercase; font-size:11px;
  color:#7fe3e2; font-weight:700; margin-bottom:12px;
}
.hero h1 {
  font-size:clamp(32px,5vw,56px); font-weight:800; line-height:1.05;
  background:linear-gradient(90deg,#fff,#b9d8ff 60%,#8ff4ee);
  -webkit-background-clip:text; background-clip:text; color:transparent;
}
.hero p {
  color:#c7d7ea; font-size:16px; margin-top:14px;
  max-width:600px; margin-inline:auto;
}
.grid {
  display:grid; grid-template-columns:repeat(auto-fill,minmax(280px,1fr));
  gap:18px; max-width:1100px; margin-inline:auto;
}
.card {
  background:rgba(255,255,255,.06); border:1px solid rgba(255,255,255,.12);
  border-radius:16px; padding:22px;
  transition:background .2s,border-color .2s;
}
.card:hover { background:rgba(255,255,255,.1); border-color:rgba(255,255,255,.25); }
.card-num {
  font-size:10px; color:#7fe3e2; font-weight:700;
  letter-spacing:.15em; text-transform:uppercase; margin-bottom:4px;
}
.card-title { font-size:16px; font-weight:700; margin-bottom:6px; }
.card-title a { color:#e8f0fb; text-decoration:none; }
.card-title a:hover { color:#7fe3e2; text-decoration:underline; }
.card-desc { font-size:12px; color:#9fb6d0; line-height:1.5; }
.master-link { text-align:center; margin:32px auto; }
.master-link a {
  display:inline-block; padding:14px 32px; border-radius:12px;
  background:linear-gradient(90deg,#0ea5a4,#326ce5);
  color:#fff; font-weight:700; font-size:15px; text-decoration:none;
}
.footer { text-align:center; margin-top:48px; color:#556070; font-size:12px; }
"""


def build_index(out_dir: Path) -> None:
    cards = "\n".join(
        f"""      <article class="card">
        <div class="card-num">{num}</div>
        <h2 class="card-title"><a href="{fname}">{title}</a></h2>
        <p class="card-desc">{desc}</p>
      </article>"""
        for fname, num, title, desc in BOOKS
    )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>The DevOps Architect's Path</title>
<style>
{CSS}
</style>
</head>
<body>
  <header class="hero">
    <div class="kicker">The DevOps Architect's Path - Edition 2026</div>
    <h1>DevOps Study Guide</h1>
    <p>Eight book-length treatments - from Git internals to production observability.
       Every section answers What, Why, How, and When with real-world scenarios and
       senior-architect interview questions.</p>
  </header>

  <div class="master-link">
    <a href="The-DevOps-Path.html">Open Master Overview</a>
  </div>

  <main class="grid">
{cards}
  </main>

  <footer class="footer">
    Generated by GitHub Actions &middot;
    <a href="https://github.com/karthikb35" style="color:#7fe3e2">karthikb35</a>
  </footer>
</body>
</html>
"""

    out_path = out_dir / "index.html"
    out_path.write_text(html, encoding="utf-8")
    print(f"Generated {out_path}")


if __name__ == "__main__":
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("_site")
    out.mkdir(parents=True, exist_ok=True)
    build_index(out)
